[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterCitations = "daee34ce-89f3-4625-b898-19384cb65244"
DocumenterVitepress = "4710194d-e776-4893-9690-8d956a29c365"
OnlinePortfolioSelection = "038f9fe3-14bd-47ca-b081-2e00e8c46dfa"

[compat]
DocumenterVitepress = "0.1.3"